import { Handler } from "@netlify/functions";
import { addWord } from "./lib/firestore";

const wordsList = [
  "ACHILLES",
  "ADDIE",
  "ALLEGHENY",
  "AMOCO",
  "ANGELOU",
  "ANGLICANS",
  "ANIBAL",
  "BACON",
  "BILLIE",
  "BRANCH",
  "CABRAL",
  "CAMARILLO",
  "CHIANTI",
  "CHURCH",
  "COLLINS",
  "CRECY",
  "DIOGENES",
  "EARLE",
  "EVENKI",
  "FAUSTINO",
  "FAUSTUS",
  "GENOA",
  "GEORGIAN",
  "GHATS",
  "GILDA",
  "GOLGOTHA",
  "HARLAN",
  "HILFIGER",
  "HOHENLOHE",
  "IBIZA",
  "JACQUELYN",
  "KAILUA",
  "KATHERINE",
  "KENYANS",
  "LAWRENCE",
  "MAIDENFORM",
  "MARGRETHE",
  "MARIA",
  "MARISA",
  "MATILDA",
  "MERCER",
  "MICHELE",
  "MILNE",
  "NABISCO",
  "NAMIBIANS",
  "NELSON",
  "NICOBAR",
  "OLYMPIAN",
  "PANTALOON",
  "PARAGUAYAN",
  "PASCALS",
  "PATNA",
  "POTSDAM",
  "PRIAM",
  "PRIBILOF",
  "PYRENEES",
  "RALPH",
  "RONSTADT",
  "ROSSETTI",
  "ROTTWEILER",
  "RUDOLF",
  "SELMA",
  "SENATOR",
  "SMITH",
  "STANFORD",
  "STRAVINSKY",
  "SWISSES",
  "TAIYUAN",
  "TAMMANY",
  "TIBETANS",
  "TIENANMEN",
  "TRIPITAKA",
  "TWILA",
  "VIRGO",
  "WALDENSIAN",
  "WALKMAN",
  "WEBERN",
  "WOTAN",
  "XERXES",
  "YPSILANTI",
];

const handler: Handler = async () => {
  await wordsList.forEach((word) => {
    addWord(word.toLowerCase().trim());
  });

  const message = "Added words";
  return {
    statusCode: 200,
    body: JSON.stringify({ message }),
  };
};

export { handler };
